In [2]:
# list
print([1,2,3])
# one dimentional array
# array([1,2,3])


[1, 2, 3]


In [3]:
#list of lists
print([[1,2,3],[4,5,6]])
# two diemntional array
# array([[1,2,3],[4,5,6]])

[[1, 2, 3], [4, 5, 6]]


In [4]:
# To install Numpy
# pip install numpy

In [5]:
import numpy as np


In [6]:
# 1_D array
a = np.array([1,2,3])
print(a)

[1 2 3]


In [7]:
# 2_D array
a = np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [8]:

# Creating an array filled with zeros
a = np.zeros(5)
print(a)

[0. 0. 0. 0. 0.]


In [9]:
# Creating an array filled with ones
a = np.ones(5)
print(a)

[1. 1. 1. 1. 1.]


In [10]:

# Creating an array of random values (shown as 2x3 matrix)
a = np.random.random((2,3))
print(a)

[[0.90273301 0.82934346 0.94341073]
 [0.78000602 0.51815677 0.19468576]]


In [11]:
# Creating an array filled with given value (dimensions, value)
a = np.full(3,10)
print(a)
a = np.full((2,3),10)
print(a)

[10 10 10]
[[10 10 10]
 [10 10 10]]


In [12]:

# Creating an empty array (fills with arbitrary, un-initialized values)
a = np.empty(2)
print(a)
a = np.empty((2,3))
print(a)

[-2.0000000e+000  6.9525372e-310]
[[0.90273301 0.82934346 0.94341073]
 [0.78000602 0.51815677 0.19468576]]


In [13]:
# Creating an array of evenly spaced values (start, stop, step)
# no include stop value
a = np.arange(1,10,1)
print(a)

[1 2 3 4 5 6 7 8 9]


In [14]:

# Creating an array of evenly spaced values (low, high, num-values)
# include stop value
a = np.linspace(1,10,10)
print(a)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [15]:
# Creating an array of random integers (low, high, size)
a = np.random.randint(1,10,10)
print(a)

[7 8 6 7 8 5 2 9 8 5]


In [16]:
my_1d_array = np.arange(0,20,1)
print(my_1d_array)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [17]:
print("Max" , my_1d_array.max())

print("Min", my_1d_array.min())

print("Mean", my_1d_array.mean())

print("Sum", my_1d_array.sum())

print("Std", my_1d_array.std())

Max 19
Min 0
Mean 9.5
Sum 190
Std 5.766281297335398


In [18]:
a = my_1d_array + 10
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]


In [19]:
a = my_1d_array - 10
print(a)

[-10  -9  -8  -7  -6  -5  -4  -3  -2  -1   0   1   2   3   4   5   6   7
   8   9]


In [20]:
a = my_1d_array * 10
print(a)

[  0  10  20  30  40  50  60  70  80  90 100 110 120 130 140 150 160 170
 180 190]


In [21]:
a = my_1d_array / 10
print(a)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7
 1.8 1.9]


In [22]:
a = np.square(my_1d_array)
print(a)

[  0   1   4   9  16  25  36  49  64  81 100 121 144 169 196 225 256 289
 324 361]


In [23]:
a = np.sqrt(my_1d_array)
print(a)

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.         3.16227766 3.31662479
 3.46410162 3.60555128 3.74165739 3.87298335 4.         4.12310563
 4.24264069 4.35889894]


In [24]:
a = np.sin(my_1d_array)
print(a)

[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427
 -0.2794155   0.6569866   0.98935825  0.41211849 -0.54402111 -0.99999021
 -0.53657292  0.42016704  0.99060736  0.65028784 -0.28790332 -0.96139749
 -0.75098725  0.14987721]


In [25]:
a = np.cos(my_1d_array)
print(a)

[ 1.          0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219
  0.96017029  0.75390225 -0.14550003 -0.91113026 -0.83907153  0.0044257
  0.84385396  0.90744678  0.13673722 -0.75968791 -0.95765948 -0.27516334
  0.66031671  0.98870462]


In [26]:
a = np.tan(my_1d_array)
print(a)

[ 0.00000000e+00  1.55740772e+00 -2.18503986e+00 -1.42546543e-01
  1.15782128e+00 -3.38051501e+00 -2.91006191e-01  8.71447983e-01
 -6.79971146e+00 -4.52315659e-01  6.48360827e-01 -2.25950846e+02
 -6.35859929e-01  4.63021133e-01  7.24460662e+00 -8.55993401e-01
  3.00632242e-01  3.49391565e+00 -1.13731371e+00  1.51589471e-01]


In [27]:
a = np.sign(my_1d_array)
print(a)

[0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


In [28]:
a = my_1d_array[0]
print(a)

0


In [29]:
a = my_1d_array[0:6]  # not include the last one
print(a)

[0 1 2 3 4 5]


In [30]:
a = my_1d_array[-1]
print(a)

19


In [70]:
a = my_1d_array.reshape(1,my_1d_array.size)
print(a)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]]


In [71]:
a = my_1d_array.reshape(my_1d_array.size,1)
print(a)

[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]]


In [31]:
my_2d_array = np.random.randint(1,10,(2,3))

print(my_2d_array)

[[8 2 8]
 [6 9 5]]


In [78]:
print("Max" , my_2d_array.max())

print("Max in column" , my_2d_array.max(axis = 0))

print("Max in row" , my_2d_array.max(axis = 1))

print("Sum of coulmn" , my_2d_array.sum(axis = 0))

print("Sum of rows" , my_2d_array.sum(axis = 1))

print("Min", my_2d_array.min())

print("Mean", my_2d_array.mean())

print("Sum", my_2d_array.sum())

print("Std", my_2d_array.std())

Max 9
Max in column [8 9 8]
Max in row [8 9]
Sum of coulmn [14 11 13]
Sum of rows [18 20]
Min 2
Mean 6.333333333333333
Sum 38
Std 2.3570226039551585


In [34]:
a = my_2d_array[0]
print(a)

[8 2 8]


In [37]:
a = my_2d_array[0][1]
print(a)

2


In [39]:
# Re-shape (here to 3 rows & 2 columns)
a = my_2d_array.reshape(3,2)
print(my_2d_array)
print(a)

[[8 2 8]
 [6 9 5]]
[[8 2]
 [8 6]
 [9 5]]


In [42]:
# Re-shape (here to a 1-Dimensional array)
a = my_2d_array.flatten()
print(a)

a = my_2d_array.reshape(6)
print(a)

a = my_2d_array.ravel()
print(a)

[8 2 8 6 9 5]
[8 2 8 6 9 5]
[8 2 8 6 9 5]


In [58]:
# Array Shape (length of each dimension)
a = my_2d_array.shape
print(a)

(2, 3)


In [59]:
# Number of dimensions
a = my_2d_array.ndim
print(a)

2


In [60]:
# Number of elements
a = my_2d_array.size
print(a)

6


In [62]:
a = my_2d_array.dtype
print(a)

int64


In [46]:
b = np.array([1,2,3])
c = np.array([4,2,6])
print("b", b)
print("c", c)

b [1 2 3]
c [4 2 6]


In [47]:
a = np.add(b,c)
print(a)

[5 4 9]


In [48]:
a = np.subtract(b,c)
print(a)

[-3  0 -3]


In [49]:
a = np.multiply(b,c)
print(a)

[ 4  4 18]


In [50]:
a = np.divide(b,c)
print(a)

[0.25 1.   0.5 ]


In [51]:
a = np.dot(b,c)
print(a)

26


In [52]:
a = (b == c)
print(a)

[False  True False]


In [53]:
a = np.array_equal(a,b)
print(a)

False


In [134]:
# Horizontal Stack
# hstack concatenates arrays along axis 1
a = np.hstack((b,c))
print(a)
print()
a = np.concatenate((b,c))
print(a)

[1 2 3 4 2 6]

[1 2 3 4 2 6]


In [140]:
# Vertical Stack
# vstack concatenates arrays along axis 0
a = np.vstack((b,c))
print(a)
print()

x = np.array([[1,2],[3,4]])
y = np.array([[5,6]])
a = np.concatenate((x,y), axis = 0)
a1 = np.vstack((x,y))
print(a)
print(a1)

[[1 2 3]
 [4 2 6]]

[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [61]:
p = np.pi
print(p)

3.141592653589793


In [63]:
a = np.array([1,2,3], dtype = np.float32)
print(a)

[1. 2. 3.]


In [67]:
#Return a 2-D array with ones on the diagonal and zero elsewhere
a = np.eye(3) # with 3 column
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [74]:
a = np.arange(12).reshape(2,2,3)
print(a)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [147]:
# Arrays can be transposed using the .T attribute
a = my_1d_array.T
a1 = my_1d_array.transpose()
print(a)
print(a1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [79]:
#Numpy also provides a set of element-wise functions that can be applied to all elements of an array, creating a new array
a = np.array([[1,2,3],[4,5,6]])
a1 = np.exp(a)
print(a1)
a2 = np.log(a)
print(a2)

[[  2.71828183   7.3890561   20.08553692]
 [ 54.59815003 148.4131591  403.42879349]]
[[0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947]]


In [80]:
# execution time
s = 0
N = 10000000
x = np.arange(N)
for i in x:
  s += i

In [81]:
# execution time
N = 10000000
x = np.arange(N)
s = x.sum()

In [104]:
x = np.arange(15).reshape(3,5)
print(x)

print()
a = x[1, 0:3]
print(a)

print()
a = x[0:2, 0:2]
print(a)

print()
idx = np.array([0, 0, 2])
#means "select the rows of x indexed by idx and all columns (: means all columns)."
a = x[idx, :]
print(a)

print()
#means "select all rows (:) and the columns of x indexed by idx."
a = x[ :,idx]
print(a)

print()
idx = np.array([0,2]) # rows
jdx = np.array([1,3]) # columns
a = x[idx, :][:,jdx]
print(a)

print()
#_ix allows you to create a 2D array by selecting all combinations of rows in idx and columns in jdx
a = x[np.ix_(idx, jdx)] # generates two 2D arrays that can be used to index the original array x:
print(a)

print()
xMask = x > 5
print(xMask)

print()
a = x[xMask]
print(a)

print()
z = np.array([1,0,1], dtype= np.bool_)
print(z)
a = x[z] # z = [True, False, True] -> x[z] = first row and second row
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

[5 6 7]

[[0 1]
 [5 6]]

[[ 0  1  2  3  4]
 [ 0  1  2  3  4]
 [10 11 12 13 14]]

[[ 0  0  2]
 [ 5  5  7]
 [10 10 12]]

[[ 1  3]
 [11 13]]

[[ 1  3]
 [11 13]]

[[False False False False False]
 [False  True  True  True  True]
 [ True  True  True  True  True]]

[ 6  7  8  9 10 11 12 13 14]

[ True False  True]
[[ 0  1  2  3  4]
 [10 11 12 13 14]]


In [110]:
x = np.zeros(6)
print(x)
x[::2] = 3
print(x)


[0. 0. 0. 0. 0. 0.]
[3. 0. 3. 0. 3. 0.]


In [111]:
x[np.array([True, False, True, True, True, False],dtype=np.bool_)] = np.arange(4)
# [0,2,3,4] = [1,2,3,4]
print(x)

[0. 0. 1. 2. 3. 0.]


In [113]:
# copy of the data
x = np.arange(6)
a = x.flags.owndata
print(a)

# view of the data
a = x[:3]
print(a.flags.owndata)


True
False


In [116]:
#Array m is broadcasted to a shape (1, 4), and then replicated along axis 0
x = np.zeros((3,4))
print(x)
print()

m = np.arange(4)
print(m)
print()

a = x + m
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[0 1 2 3]

[[0. 1. 2. 3.]
 [0. 1. 2. 3.]
 [0. 1. 2. 3.]]


In [117]:
# Array m already has the same number of dimensions as x, and gets replicated along axis 0
x = np.zeros((3,4))
print(x)
print()

m = np.arange(4).reshape((1,4))
print(m)
print()

a = x + m
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[0 1 2 3]]

[[0. 1. 2. 3.]
 [0. 1. 2. 3.]
 [0. 1. 2. 3.]]


In [118]:
#Array m already has the same number of dimensions as x, and gets replicated along axis 1
x = np.zeros((3,4))
print(x)
print()

m = np.arange(3).reshape((3,1))
print(m)
print()

a = x + m
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[0]
 [1]
 [2]]

[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]]


In [126]:
# linear algebra functions
# compute the eigenvalue decomposition of a 2-D array
x = np.arange(9).reshape(3,3)
a = np.linalg.eig(x)
print(a)

EigResult(eigenvalues=array([ 1.33484692e+01, -1.34846923e+00, -2.48477279e-16]), eigenvectors=array([[ 0.16476382,  0.79969966,  0.40824829],
       [ 0.50577448,  0.10420579, -0.81649658],
       [ 0.84678513, -0.59128809,  0.40824829]]))


In [133]:
x = np.array([99,1,109,-1])
print(x)
print()

a = np.argsort(x) # index of the sorted array
print(a)
print()

a = np.sort(x)
print(a)
print()

[ 99   1 109  -1]

[3 1 0 2]

[ -1   1  99 109]



In [146]:
x = np.array([99,2,109,-1])
print(x[x>100])
print(x[(x>100) | (x < 0)])
print(x[(x % 2) == 0 ])

[109]
[109  -1]
[2]


In [149]:
x = np.array([99,2,109,-1])
print(x)
a = np.flip(x)
print(a)

[ 99   2 109  -1]
[ -1 109   2  99]


In [152]:
x = np.array([[1,2,3],[4,5,6]])
print(x)
print()

a = np.flip(x)
print(a)
print()

a1 = np.flip(x, axis=0) #column
print(a1)
print()

a2 = np.flip(x, axis=1) #row
print(a2)
print()

[[1 2 3]
 [4 5 6]]

[[6 5 4]
 [3 2 1]]

[[4 5 6]
 [1 2 3]]

[[3 2 1]
 [6 5 4]]



In [ ]:
#save array in a file
#np.save('filename' , array)

#load file
#np.load('filename.py')
