In [119]:
# list
print([1,2,3])
# one dimentional array
# array([1,2,3])


[1, 2, 3]


In [120]:
#list of lists
print([[1,2,3],[4,5,6]])
# two diemntional array
# array([[1,2,3],[4,5,6]])

[[1, 2, 3], [4, 5, 6]]


In [121]:
# To install Numpy
# pip install numpy

In [122]:
import numpy as np


In [123]:
# 1D array
# Vector
a = np.array([1,2,3])
print(a)

[1 2 3]


In [124]:
# 2D array
# Matrics
a = np.array([[1,2,3],[4,5,6]])
print(a,a.size,a.shape,a.ndim,a.dtype)


[[1 2 3]
 [4 5 6]] 6 (2, 3) 2 int64


In [125]:
a = np.array([1,2,3], dtype= np.float64)
a

array([1., 2., 3.])

In [126]:
b = np.array(a) #as a copy of another array
b

array([1., 2., 3.])

In [127]:
# Creating an array filled with zeros
a = np.zeros(5)
print(a)

[0. 0. 0. 0. 0.]


In [128]:
a = np.zeros((2,3), dtype=np.int64)
print(a)

[[0 0 0]
 [0 0 0]]


In [129]:
# Creating an array filled with ones
a = np.ones(5)
print(a)

[1. 1. 1. 1. 1.]


In [130]:
a = np.ones((2,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [131]:
# Creating an array of random values (shown as 2x3 matrix)
a = np.random.random((2,3))
print(a)

[[0.10504747 0.0328721  0.63601711]
 [0.89439466 0.24409084 0.39248074]]


In [132]:
# Creating an array filled with given value (dimensions, value)
a = np.full(3,10) #(1,3)
print(a)
print(" -------- ")
a = np.full((2,3),10)
print(a)

[10 10 10]
 -------- 
[[10 10 10]
 [10 10 10]]


In [133]:
# Creating an empty array (fills with arbitrary, un-initialized values)
a = np.empty(2)
print(a)
print(" -------- ")
a = np.empty((2,3))
print(a)

[3.5e-323 4.9e-323]
 -------- 
[[5.e-323 5.e-323 5.e-323]
 [5.e-323 5.e-323 5.e-323]]


In [134]:
# Creating an array of evenly spaced values (start, stop, step)
# no include stop value
a = np.arange(1,10,1)
print(a)
print(" ------- ")
a = np.arange(1,10,2)
print(a)

[1 2 3 4 5 6 7 8 9]
 ------- 
[1 3 5 7 9]


In [135]:
a = np.arange(3)
print(a)

[0 1 2]


In [136]:
# eye is a function used to create a 2D identity matrix or a matrix with ones on a specified diagonal and zeros elsewhere.
# identity matrix eye(M,N,K=0)
a = np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [137]:
# k = 1
a = np.eye(3,3,1)
print(a)

[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


In [138]:
# k = -1
a = np.eye(3,3,-1)
print(a)

[[0. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]


In [139]:
# k = -2
a = np.eye(3,3,-2)
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [1. 0. 0.]]


In [140]:
np.diag([10, 20, 30])

array([[10,  0,  0],
       [ 0, 20,  0],
       [ 0,  0, 30]])

In [141]:
np.diag([10, 20, 30], 1)

array([[ 0, 10,  0,  0],
       [ 0,  0, 20,  0],
       [ 0,  0,  0, 30],
       [ 0,  0,  0,  0]])

In [142]:
np.tri(4,4)

array([[1., 0., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 1., 0.],
       [1., 1., 1., 1.]])

In [143]:
np.tri(4,4,k=-1)

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 1., 0.]])

In [144]:
np.triu(np.ones((4,4)))

array([[1., 1., 1., 1.],
       [0., 1., 1., 1.],
       [0., 0., 1., 1.],
       [0., 0., 0., 1.]])

In [145]:
np.triu(np.ones((4,4)), k=1)

array([[0., 1., 1., 1.],
       [0., 0., 1., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [146]:
# Creating an array of evenly spaced values (low, high, num-values)
# include stop value
a = np.linspace(1,10,9)
print(a)

[ 1.     2.125  3.25   4.375  5.5    6.625  7.75   8.875 10.   ]


In [147]:
# Creating an array of random integers (low, high, size)
a = np.random.randint(1,10,15)
print(a)

[5 5 8 7 1 3 3 5 8 1 6 5 2 1 6]


In [148]:
my_1d_array = np.arange(0,20,5)
print(my_1d_array)

[ 0  5 10 15]


In [149]:
print("Max" , my_1d_array.max())

print("Min", my_1d_array.min())

print("Mean", my_1d_array.mean())

print("Sum", my_1d_array.sum())

print("Std", my_1d_array.std())

Max 15
Min 0
Mean 7.5
Sum 30
Std 5.5901699437494745


In [150]:
a = my_1d_array + 10
print(a)

[10 15 20 25]


In [151]:
a = my_1d_array - 10
print(a)

[-10  -5   0   5]


In [152]:
a = my_1d_array * 10
print(a)

[  0  50 100 150]


In [153]:
a = my_1d_array / 10
print(a)

[0.  0.5 1.  1.5]


In [154]:
a = np.square(my_1d_array)
print(a)

[  0  25 100 225]


In [155]:
a = np.sqrt(my_1d_array)
print(a)

[0.         2.23606798 3.16227766 3.87298335]


In [156]:
a = np.sin(my_1d_array)
print(a)

[ 0.         -0.95892427 -0.54402111  0.65028784]


In [157]:
a = np.cos(my_1d_array)
print(a)

[ 1.          0.28366219 -0.83907153 -0.75968791]


In [158]:
a = np.tan(my_1d_array)
print(a)

[ 0.         -3.38051501  0.64836083 -0.8559934 ]


In [159]:
a = np.sign(my_1d_array)
print(a)

# + 1
# - -1
# 0 0

[0 1 1 1]


In [160]:
a = my_1d_array[0]
print(a)

0


In [161]:
a = my_1d_array[0:6]  # not include the last one
print(a)

[ 0  5 10 15]


In [162]:
a = my_1d_array[-1]
print(a)

15


In [163]:
a = my_1d_array.reshape(1,my_1d_array.size)
print(a)

[[ 0  5 10 15]]


In [164]:
a = my_1d_array.reshape(my_1d_array.size,1)
print(a)

[[ 0]
 [ 5]
 [10]
 [15]]


In [165]:
my_2d_array = np.random.randint(1,5,(2,3))

print(my_2d_array)

[[1 3 3]
 [4 1 2]]


In [166]:
print("Max" , my_2d_array.max())

print("Max in column" , my_2d_array.max(axis = 0))

print("Max in row" , my_2d_array.max(axis = 1))

print("Sum of coulmn" , my_2d_array.sum(axis = 0))

print("Sum of rows" , my_2d_array.sum(axis = 1))

print("Min", my_2d_array.min())

print("Mean", my_2d_array.mean())

print("Sum", my_2d_array.sum())

print("Std", my_2d_array.std())

Max 4
Max in column [4 3 3]
Max in row [3 4]
Sum of coulmn [5 4 5]
Sum of rows [7 7]
Min 1
Mean 2.3333333333333335
Sum 14
Std 1.1055415967851332


In [167]:
a = my_2d_array[0]
print(a)

[1 3 3]


In [168]:
a = my_2d_array[0][1]
print(a)

3


In [169]:
x =np.array([[1,2],[3,4],[5,6]])
y = np .array([[1,2,3],[4,5,6]])
np.dot(x,y)

array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]])

In [170]:
# Re-shape (here to 3 rows & 2 columns)

print(a)
print(" ------- ")
a = my_2d_array.reshape(3,2)
print(my_2d_array)


3
 ------- 
[[1 3 3]
 [4 1 2]]


In [171]:
x = np.arange(12).reshape((2,2,3)) #2 blocks each block (2,3)
x

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [172]:
print(x)
print(" --- 1D --- " )
x.ravel()

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
 --- 1D --- 


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [173]:
# Re-shape (here to a 1-Dimensional array)
print(" --- ND to 1D --- " )

a = x.flatten()
print(a)
print(" --- ND to 1D --- " )

a = x.reshape(12)
print(a)

print(" --- ND to 1D --- " )

a = x.ravel()
print(a)

 --- ND to 1D --- 
[ 0  1  2  3  4  5  6  7  8  9 10 11]
 --- ND to 1D --- 
[ 0  1  2  3  4  5  6  7  8  9 10 11]
 --- ND to 1D --- 
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [174]:
# Array Shape (length of each dimension)
a = my_2d_array.shape
print(a)

(2, 3)


In [175]:
# Number of dimensions
a = my_2d_array.ndim
print(a)

2


In [176]:
# Number of elements
a = my_2d_array.size
print(a)

6


In [177]:
a = my_2d_array.dtype
print(a)

int64


In [178]:
b = np.array([1,2,3])
c = np.array([4,2,6])
print("b", b)
print("c", c)

b [1 2 3]
c [4 2 6]


In [179]:
a = np.add(b,c)
print(a)

[5 4 9]


In [180]:
a = np.subtract(b,c)
print(a)

[-3  0 -3]


In [181]:
a = np.multiply(b,c)
print(a)

[ 4  4 18]


In [182]:
a = np.divide(b,c)
print(a)

[0.25 1.   0.5 ]


In [183]:
a = np.dot(b,c)
print(a)

26


In [184]:
a = (b == c)
print(a)

[False  True False]


In [185]:
a = np.array_equal(a,b)
print(a)

False


In [186]:
x = np.arange(3).reshape((3,1))

print(x)
print("---- T ----")
y = x.T

print(y)

[[0]
 [1]
 [2]]
---- T ----
[[0 1 2]]


In [245]:
# Horizontal Stack
# hstack concatenates arrays along axis 1
a = np.hstack((b,c))
print(a)
print(" ----- ")
a = np.concatenate((b,c))
print(a)

[1 2 3 4 2 6]
 ----- 
[1 2 3 4 2 6]


In [246]:
# Vertical Stack
# vstack concatenates arrays along axis 0
a = np.vstack((b,c))
print(a)
print(" ----- ")

x = np.array([[1,2],[3,4]])
y = np.array([[5,6]])
a = np.concatenate((x,y))
a1 = np.vstack((x,y))
print(a)
print(" ----- ")
print(a1)

[[1 2 3]
 [4 2 6]]
 ----- 
[[1 2]
 [3 4]
 [5 6]]
 ----- 
[[1 2]
 [3 4]
 [5 6]]


In [247]:
p = np.pi
print(p)

3.141592653589793


In [190]:
a = np.array([1,2,3], dtype = np.float32)
print(a)

[1. 2. 3.]


In [191]:
#Return a 2-D array with ones on the diagonal and zero elsewhere
a = np.eye(3) # with 3 column
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [192]:
a = np.arange(12).reshape(2,2,3)
print(a)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [249]:
# Arrays can be transposed using the .T attribute
a = my_1d_array.T
a1 = my_1d_array.transpose()
print(a)
print(" ----- ")
print(a1)

[ 0  5 10 15]
 ----- 
[ 0  5 10 15]


In [250]:
# Numpy also provides a set of element-wise functions that can be applied to all elements of an array, creating a new array
a = np.array([[1,2,3],[4,5,6]])
print(a)
print(" ----- ")
a1 = np.exp(a) # e^x
print(a1)
print(" ----- ")
a2 = np.log(a)
print(a2)

[[1 2 3]
 [4 5 6]]
 ----- 
[[  2.71828183   7.3890561   20.08553692]
 [ 54.59815003 148.4131591  403.42879349]]
 ----- 
[[0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947]]


In [251]:
# execution time
s = 0
N = 10000000
x = np.arange(N)
for i in x:
  s += i

In [252]:
# execution time
N = 10000000
x = np.arange(N)
s = x.sum()

In [254]:
x = np.arange(15).reshape(3,5)
print(x)
print(" ----- ")
a = x[1, 0:3] # first row and column 1, 2, 3
print(a)
print(" ----- ")
a = x[0:2, 0:2] # row:0,1 column 0,1
print(a)
print(" ----- ")
idx = np.array([0, 0, 2])
#means "select the rows of x indexed by idx and all columns (: means all columns)."
a = x[idx, :]
print(a)
print(" ----- ")
#means "select all rows (:) and the columns of x indexed by idx."
a = x[ :,idx]
print(a)
print(" ----- ")
idx = np.array([0,2]) # rows
jdx = np.array([1,3]) # columns
a = x[idx, :][:,jdx]
print(a)
print(" ----- ")
#_ix allows you to create a 2D array by selecting all combinations of rows in idx and columns in jdx
a = x[np.ix_(idx, jdx)] # generates two 2D arrays that can be used to index the original array x:
print(a)
print(" ----- ")
xMask = x > 5
print(xMask)
print(" ----- ")
a = x[xMask]
print(a)
print(" ----- ")
z = np.array([1,0,1], dtype= np.bool_)
print(z)
print(" ----- ")
a = x[z] # z = [True, False, True] -> x[z] = first row and second row
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
 ----- 
[5 6 7]
 ----- 
[[0 1]
 [5 6]]
 ----- 
[[ 0  1  2  3  4]
 [ 0  1  2  3  4]
 [10 11 12 13 14]]
 ----- 
[[ 0  0  2]
 [ 5  5  7]
 [10 10 12]]
 ----- 
[[ 1  3]
 [11 13]]
 ----- 
[[ 1  3]
 [11 13]]
 ----- 
[[False False False False False]
 [False  True  True  True  True]
 [ True  True  True  True  True]]
 ----- 
[ 6  7  8  9 10 11 12 13 14]
 ----- 
[ True False  True]
 ----- 
[[ 0  1  2  3  4]
 [10 11 12 13 14]]


In [258]:
x = np.zeros(6)
print(x)
print(" ----- ")
x[::2] = 3
print(x)


[0. 0. 0. 0. 0. 0.]
 ----- 
[3. 0. 3. 0. 3. 0.]


In [259]:
print(x)
print(" ----- ")
x[np.array([True, False, True, True, True, False],dtype=np.bool_)] = np.arange(4) # index 0,2,3,4
# np.arange(4) -> [0,1,2,3]
print(x)

[3. 0. 3. 0. 3. 0.]
 ----- 
[0. 0. 1. 2. 3. 0.]


In [261]:
# copy of the data
x = np.arange(6)
a = x.flags.owndata # not copy
print(a)
print(" ----- ")
# view of the data
a = x[:3]
print(a.flags.owndata) # copy of array x


True
 ----- 
False


In [262]:
#Array m is broadcasted to a shape (1, 4), and then replicated along axis 0
x = np.zeros((3,4))
print(x)
print(" ----- ")

m = np.arange(4)
print(m)
print(" ----- ")

a = x + m
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
 ----- 
[0 1 2 3]
 ----- 
[[0. 1. 2. 3.]
 [0. 1. 2. 3.]
 [0. 1. 2. 3.]]


In [263]:
# Array m already has the same number of dimensions as x, and gets replicated along axis 0
x = np.zeros((3,4))
print(x)
print(" ----- ")

m = np.arange(4).reshape((1,4))
print(m)
print(" ----- ")

a = x + m
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
 ----- 
[[0 1 2 3]]
 ----- 
[[0. 1. 2. 3.]
 [0. 1. 2. 3.]
 [0. 1. 2. 3.]]


In [264]:
#Array m already has the same number of dimensions as x, and gets replicated along axis 1
x = np.zeros((3,4))
print(x)
print(" ----- ")

m = np.arange(3).reshape((3,1))
print(m)
print(" ----- ")

a = x + m
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
 ----- 
[[0]
 [1]
 [2]]
 ----- 
[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]]


In [266]:
# linear algebra functions
# compute the eigenvalue decomposition and eigenvectors of a 2-D array
# A v = lambda v
x = np.arange(9).reshape(3,3)
print(x)
print(" ----- ")
a = np.linalg.eig(x)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
 ----- 
EigResult(eigenvalues=array([ 1.33484692e+01, -1.34846923e+00, -2.48477279e-16]), eigenvectors=array([[ 0.16476382,  0.79969966,  0.40824829],
       [ 0.50577448,  0.10420579, -0.81649658],
       [ 0.84678513, -0.59128809,  0.40824829]]))


In [269]:
x = np.array([99,1,109,-1])
print(x)
print(" --- index of the sorted array -- ")

a = np.argsort(x) # index of the sorted array
print(a)
print(" ----- ")

a = np.sort(x)
print(a)


[ 99   1 109  -1]
 --- index of the sorted array -- 
[3 1 0 2]
 ----- 
[ -1   1  99 109]


In [206]:
x = np.array([99,2,109,-1])
print(x[x>100])
print(x[(x>100) | (x < 0)])
print(x[(x % 2) == 0 ])

[109]
[109  -1]
[2]


In [271]:
x = np.array([99,2,109,-1])
print(x)
print(" --- Reverse --- ")
a = np.flip(x)
print(a)

[ 99   2 109  -1]
 --- Reverse --- 
[ -1 109   2  99]


In [276]:
x = np.array([[1,2,3],[4,5,6]])
print(x)
print(" -- reverse x and reverse y--- ")

a = np.flip(x)
print(a)
print(" --- reverse row -- ")

a1 = np.flip(x, axis=0) #column
print(a1)
print(" --- reverse column -- ")

a2 = np.flip(x, axis=1) #row
print(a2)


[[1 2 3]
 [4 5 6]]
 -- reverse x and reverse y--- 
[[6 5 4]
 [3 2 1]]
 --- reverse row -- 
[[4 5 6]
 [1 2 3]]
 --- reverse column -- 
[[3 2 1]
 [6 5 4]]


In [209]:
#save array in a file
#np.save('filename' , array)

#load file
#np.load('filename.py')


In [277]:
s =0
N= 10000000
x = np.arange(N)
for i in x:
  s += i

#3s

In [278]:
N= 10000000
x = np.arange(N)

s = x.sum()
#0.127s

In [279]:
x = np.arange(5)
print(x,"--->",x[1:3],x[::2],x[3])

[0 1 2 3 4] ---> [1 2] [0 2 4] 3


In [213]:
x = np.arange(15).reshape(3,5)
print(x, "------", x[1,0:3], x[0:2, 0:2])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]] ------ [5 6 7] [[0 1]
 [5 6]]


In [280]:
idx = np.array([0,0,2])
print(idx)

[0 0 2]


In [215]:
print(x[idx,:]) #x[[0,0,2], :] [row 0, row 0, row 2]

[[ 0  1  2  3  4]
 [ 0  1  2  3  4]
 [10 11 12 13 14]]


In [216]:
 #x[:, [0,0,2]] [column 0, column 0, column 2]
x[:,idx]

array([[ 0,  0,  2],
       [ 5,  5,  7],
       [10, 10, 12]])

In [217]:
 #x[0,0] x[0,0] x[2,2]
x[idx,idx]

array([ 0,  0, 12])

In [218]:
x[idx,:][:,idx]

array([[ 0,  0,  2],
       [ 0,  0,  2],
       [10, 10, 12]])

In [219]:
idx = np.array([0,2])
jdx = np.array([1,3])

In [220]:
#extract all rows in idx and all columns in jdx
#first way

x[idx,:][:,jdx]

array([[ 1,  3],
       [11, 13]])

In [221]:
#second way
x[np.ix_(idx,jdx)]

array([[ 1,  3],
       [11, 13]])

In [222]:
x[idx.reshape((2,1)),jdx.reshape((1,2))]

array([[ 1,  3],
       [11, 13]])

In [223]:
xMask = x>5
print(xMask)

[[False False False False False]
 [False  True  True  True  True]
 [ True  True  True  True  True]]


In [224]:
x[xMask]


array([ 6,  7,  8,  9, 10, 11, 12, 13, 14])

In [225]:
z = np.array([1,0,1], dtype =np.bool)
z

array([ True, False,  True])

In [226]:
x[z]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14]])

In [227]:
x = np.zeros(6)
x

array([0., 0., 0., 0., 0., 0.])

In [228]:
x[::2] = 3 #select every second element, starting from index 0
x

array([3., 0., 3., 0., 3., 0.])

In [229]:
x[np.array([True, False, True, True, True, False], dtype = np.bool)] = np.arange(4)
x
#[0,2,3,4]

array([0., 0., 1., 2., 3., 0.])

In [230]:
x = np.arange(5)
y = x[0:3]
y[:] = 3
print(x)

[3 3 3 3 4]


In [231]:
x = np.arange(5)
x.flags.owndata

True

In [232]:
y = x[0:3]
y.flags.owndata

False

In [233]:
x = np.zeros((3,4))
m = np.arange(4) #m is brodcasted to a shape(1,4) and then replicated along axis 0
print(x+m)

[[0. 1. 2. 3.]
 [0. 1. 2. 3.]
 [0. 1. 2. 3.]]


In [234]:
x = np.zeros((3,4))
m = np.arange(4).reshape((1,4))
x + m

array([[0., 1., 2., 3.],
       [0., 1., 2., 3.],
       [0., 1., 2., 3.]])

In [235]:
x = np.zeros((3,4))
m = np.arange(3).reshape((3,1))
x + m

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.]])

In [236]:
x1 = np.array([[1,2,3]])
x2 = np.array([[4,5,6]])
print(x1,x2)

[[1 2 3]] [[4 5 6]]


In [237]:
np.hstack([x1,x2]) #concatenates arrays along axis 1

array([[1, 2, 3, 4, 5, 6]])

In [238]:
np.vstack([x1,x2]) #concatenates arrays along axis 0

array([[1, 2, 3],
       [4, 5, 6]])

In [239]:
np.concatenate([x1,x2],axis=1) #hstack

array([[1, 2, 3, 4, 5, 6]])

In [240]:
np.concatenate([x1,x2],axis=0) #vstack

array([[1, 2, 3],
       [4, 5, 6]])

In [241]:
x = np.arange(9).reshape(3,3)
np.linalg.eig(x)

EigResult(eigenvalues=array([ 1.33484692e+01, -1.34846923e+00, -2.48477279e-16]), eigenvectors=array([[ 0.16476382,  0.79969966,  0.40824829],
       [ 0.50577448,  0.10420579, -0.81649658],
       [ 0.84678513, -0.59128809,  0.40824829]]))