In [2]:
# list
print([1,2,3])
# one dimentional array
# array([1,2,3])


[1, 2, 3]

In [3]:
#list of lists
print([[1,2,3],[4,5,6]])
# two diemntional array
# array([[1,2,3],[4,5,6]])

[[1, 2, 3], [4, 5, 6]]

In [ ]:
# To install Numpy
# pip install numpy

In [4]:
import numpy as np


In [ ]:
# 1_D array
a = np.array([1,2,3])
print(a)

array([1, 2, 3])

In [ ]:
# 2_D array
a = np.array([[1,2,3],[4,5,6]])
print(a)

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:

# Creating an array filled with zeros
a = np.zeros(5)
print(a)

array([0., 0., 0., 0., 0.])

In [ ]:
# Creating an array filled with ones
a = np.ones(5)
print(a)

array([1., 1., 1., 1., 1.])

In [ ]:

# Creating an array of random values (shown as 2x3 matrix)
a = np.random.random((2,3))
print(a)

array([[0.6333859 , 0.22633832, 0.77566884],
       [0.85774802, 0.79923427, 0.90513013]])

In [5]:
# Creating an array filled with given value (dimensions, value)
a = np.full(3,10)
print(a)
a = np.full((2,3),10)
print(a)

[10 10 10]
[[10 10 10]
 [10 10 10]]


In [ ]:

# Creating an empty array (fills with arbitrary, un-initialized values)
a = np.empty(2)
print(a)
a = np.empty((2,3))
print(a)

array([[0.6333859 , 0.22633832, 0.77566884],
       [0.85774802, 0.79923427, 0.90513013]])

In [ ]:
# Creating an array of evenly spaced values (start, stop, step)
# no include stop value
a = np.arange(1,10,1)
print(a)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:

# Creating an array of evenly spaced values (low, high, num-values)
# include stop value
a = np.linspace(1,10,10)
print(a)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
# Creating an array of random integers (low, high, size)
a = np.random.randint(1,10,10)
print(a)

In [ ]:
my_1d_array = np.arange(0,20,1)
print(my_1d_array)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
print("Max" , my_1d_array.max())

print("Min", my_1d_array.min())

print("Mean", my_1d_array.mean())

print("Sum", my_1d_array.sum())

print("Std", my_1d_array.std())

Max 19
Min 0
Mean 9.5
Sum 190
Std 5.766281297335398


In [ ]:
a = my_1d_array + 10
print(a)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29])

In [ ]:
a = my_1d_array - 10
print(a)

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,
         3,   4,   5,   6,   7,   8,   9])

In [ ]:
a = my_1d_array * 10
print(a)

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120,
       130, 140, 150, 160, 170, 180, 190])

In [ ]:
a = my_1d_array / 10
print(a)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9])

In [ ]:
a = np.square(my_1d_array)
print(a)

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361])

In [ ]:
a = np.sqrt(my_1d_array)
print(a)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894])

In [ ]:
a = np.sin(my_1d_array)
print(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736,
        0.65028784, -0.28790332, -0.96139749, -0.75098725,  0.14987721])

In [ ]:
a = np.cos(my_1d_array)
print(a)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026,
       -0.83907153,  0.0044257 ,  0.84385396,  0.90744678,  0.13673722,
       -0.75968791, -0.95765948, -0.27516334,  0.66031671,  0.98870462])

In [ ]:
a = np.tan(my_1d_array)
print(a)

array([ 0.00000000e+00,  1.55740772e+00, -2.18503986e+00, -1.42546543e-01,
        1.15782128e+00, -3.38051501e+00, -2.91006191e-01,  8.71447983e-01,
       -6.79971146e+00, -4.52315659e-01,  6.48360827e-01, -2.25950846e+02,
       -6.35859929e-01,  4.63021133e-01,  7.24460662e+00, -8.55993401e-01,
        3.00632242e-01,  3.49391565e+00, -1.13731371e+00,  1.51589471e-01])

In [ ]:
a = np.sign(my_1d_array)
print(a)

array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [ ]:
a = my_1d_array[0]
print(a)

0

In [ ]:
a = my_1d_array[0:6]  # not include the last one
print(a)

array([0, 1, 2, 3, 4, 5])

In [ ]:
a = my_1d_array[-1]
print(a)

19

In [ ]:
my_2d_array = np.random.randint(1,10,(2,3))

print(my_2d_array)

array([[7, 2, 8],
       [3, 2, 9]])

In [ ]:
print("Max" , my_2d_array.max())

print("Max in column" , my_2d_array.max(axis = 0))

print("Max in row" , my_2d_array.max(axis = 1))

print("Min", my_2d_array.min())

print("Mean", my_2d_array.mean())

print("Sum", my_2d_array.sum())

print("Std", my_2d_array.std())

Max 9
Max in column [7 2 9]
Max in row [8 9]
Min 2
Mean 5.166666666666667
Sum 31
Std 2.9107081994288304


In [ ]:
b = np.array([1,2,3])
c = np.array([4,2,6])
print("b", b)
print("c", c)

[1 2 3] [4 2 6]


In [ ]:
a = np.add(b,c)
print(a)

array([5, 4, 9])

In [ ]:
a = np.subtract(b,c)
print(a)

array([-3,  0, -3])

In [ ]:
a = np.multiply(b,c)
print(a)

array([ 4,  4, 18])

In [ ]:
a = np.divide(b,c)
print(a)

array([0.25, 1.  , 0.5 ])

In [ ]:
a = np.dot(b,c)
print(a)

26

In [ ]:
a = b == c
print(a)

array([False,  True, False])

In [ ]:
np.array_equal(a,b)

False