In [3]:
# list
print([1,2,3])
# one dimentional array
# array([1,2,3])


[1, 2, 3]


In [4]:
#list of lists
print([[1,2,3],[4,5,6]])
# two diemntional array
# array([[1,2,3],[4,5,6]])

[[1, 2, 3], [4, 5, 6]]


In [5]:
# To install Numpy
# pip install numpy

In [6]:
import numpy as np


In [7]:
# 1D array
# Vector
a = np.array([1,2,3])
print(a)

[1 2 3]


In [8]:
# 2D array
# Matrics
a = np.array([[1,2,3],[4,5,6]])
print(a,a.size,a.shape,a.ndim,a.dtype)


[[1 2 3]
 [4 5 6]] 6 (2, 3) 2 int64


In [9]:
a = np.array([1,2,3], dtype= np.float64)
a

array([1., 2., 3.])

In [10]:
b = np.array(a) #as a copy of another array
b

array([1., 2., 3.])

In [11]:
# Creating an array filled with zeros
a = np.zeros(5)
print(a)

[0. 0. 0. 0. 0.]


In [12]:
a = np.zeros((2,3), dtype=np.int64)
print(a)

[[0 0 0]
 [0 0 0]]


In [13]:
# Creating an array filled with ones
a = np.ones(5)
print(a)

[1. 1. 1. 1. 1.]


In [14]:
a = np.ones((2,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [15]:
# Creating an array of random values (shown as 2x3 matrix)
a = np.random.random((2,3))
print(a)

[[0.11716088 0.5969717  0.42481664]
 [0.89492538 0.74816441 0.5725233 ]]


In [16]:
# Creating an array filled with given value (dimensions, value)
a = np.full(3,10) #(1,3)
print(a)
print(" -------- ")
a = np.full((2,3),10)
print(a)

[10 10 10]
 -------- 
[[10 10 10]
 [10 10 10]]


In [119]:
# Creating an empty array (fills with arbitrary, un-initialized values)
a = np.empty(2)
print(a)
print(" -------- ")
a = np.empty((2,3))
print(a)

[2.5e-323 3.0e-323]
 -------- 
[[2.44694378e-315 0.00000000e+000 6.75754559e-310]
 [6.75753941e-310 5.28575934e-317 6.75754659e-310]]


In [120]:
# Creating an array of evenly spaced values (start, stop, step)
# no include stop value
a = np.arange(1,10,1)
print(a)
print(" ------- ")
a = np.arange(1,10,2)
print(a)

[1 2 3 4 5 6 7 8 9]
 ------- 
[1 3 5 7 9]


In [121]:
a = np.arange(3)
print(a)

[0 1 2]


In [122]:
# eye is a function used to create a 2D identity matrix or a matrix with ones on a specified diagonal and zeros elsewhere.
# identity matrix eye(M,N,K=0)
a = np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [123]:
# k = 1
a = np.eye(3,3,1)
print(a)

[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


In [124]:
# k = -1
a = np.eye(3,3,-1)
print(a)

[[0. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]


In [125]:
# k = -2
a = np.eye(3,3,-2)
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [1. 0. 0.]]


In [126]:
np.diag([10, 20, 30])

array([[10,  0,  0],
       [ 0, 20,  0],
       [ 0,  0, 30]])

In [127]:
np.diag([10, 20, 30], 1)

array([[ 0, 10,  0,  0],
       [ 0,  0, 20,  0],
       [ 0,  0,  0, 30],
       [ 0,  0,  0,  0]])

In [128]:
np.tri(4,4)

array([[1., 0., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 1., 0.],
       [1., 1., 1., 1.]])

In [129]:
np.tri(4,4,k=-1)

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 1., 0.]])

In [132]:
np.triu(np.ones((4,4)))

array([[1., 1., 1., 1.],
       [0., 1., 1., 1.],
       [0., 0., 1., 1.],
       [0., 0., 0., 1.]])

In [133]:
np.triu(np.ones((4,4)), k=1)

array([[0., 1., 1., 1.],
       [0., 0., 1., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [134]:
# Creating an array of evenly spaced values (low, high, num-values)
# include stop value
a = np.linspace(1,10,9)
print(a)

[ 1.     2.125  3.25   4.375  5.5    6.625  7.75   8.875 10.   ]


In [136]:
# Creating an array of random integers (low, high, size)
a = np.random.randint(1,10,15)
print(a)

[6 5 4 5 9 8 8 9 3 4 9 8 8 4 3]


In [137]:
my_1d_array = np.arange(0,20,5)
print(my_1d_array)

[ 0  5 10 15]


In [26]:
print("Max" , my_1d_array.max())

print("Min", my_1d_array.min())

print("Mean", my_1d_array.mean())

print("Sum", my_1d_array.sum())

print("Std", my_1d_array.std())

Max 19
Min 0
Mean 9.5
Sum 190
Std 5.766281297335398


In [27]:
a = my_1d_array + 10
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]


In [28]:
a = my_1d_array - 10
print(a)

[-10  -9  -8  -7  -6  -5  -4  -3  -2  -1   0   1   2   3   4   5   6   7
   8   9]


In [29]:
a = my_1d_array * 10
print(a)

[  0  10  20  30  40  50  60  70  80  90 100 110 120 130 140 150 160 170
 180 190]


In [30]:
a = my_1d_array / 10
print(a)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7
 1.8 1.9]


In [31]:
a = np.square(my_1d_array)
print(a)

[  0   1   4   9  16  25  36  49  64  81 100 121 144 169 196 225 256 289
 324 361]


In [32]:
a = np.sqrt(my_1d_array)
print(a)

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.         3.16227766 3.31662479
 3.46410162 3.60555128 3.74165739 3.87298335 4.         4.12310563
 4.24264069 4.35889894]


In [33]:
a = np.sin(my_1d_array)
print(a)

[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427
 -0.2794155   0.6569866   0.98935825  0.41211849 -0.54402111 -0.99999021
 -0.53657292  0.42016704  0.99060736  0.65028784 -0.28790332 -0.96139749
 -0.75098725  0.14987721]


In [34]:
a = np.cos(my_1d_array)
print(a)

[ 1.          0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219
  0.96017029  0.75390225 -0.14550003 -0.91113026 -0.83907153  0.0044257
  0.84385396  0.90744678  0.13673722 -0.75968791 -0.95765948 -0.27516334
  0.66031671  0.98870462]


In [35]:
a = np.tan(my_1d_array)
print(a)

[ 0.00000000e+00  1.55740772e+00 -2.18503986e+00 -1.42546543e-01
  1.15782128e+00 -3.38051501e+00 -2.91006191e-01  8.71447983e-01
 -6.79971146e+00 -4.52315659e-01  6.48360827e-01 -2.25950846e+02
 -6.35859929e-01  4.63021133e-01  7.24460662e+00 -8.55993401e-01
  3.00632242e-01  3.49391565e+00 -1.13731371e+00  1.51589471e-01]


In [36]:
a = np.sign(my_1d_array)
print(a)

# + 1
# - -1
# 0 0

[0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


In [138]:
a = my_1d_array[0]
print(a)

0


In [38]:
a = my_1d_array[0:6]  # not include the last one
print(a)

[0 1 2 3 4 5]


In [39]:
a = my_1d_array[-1]
print(a)

19


In [40]:
a = my_1d_array.reshape(1,my_1d_array.size)
print(a)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]]


In [41]:
a = my_1d_array.reshape(my_1d_array.size,1)
print(a)

[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]]


In [141]:
my_2d_array = np.random.randint(1,5,(2,3))

print(my_2d_array)

[[2 1 3]
 [1 2 1]]


In [43]:
print("Max" , my_2d_array.max())

print("Max in column" , my_2d_array.max(axis = 0))

print("Max in row" , my_2d_array.max(axis = 1))

print("Sum of coulmn" , my_2d_array.sum(axis = 0))

print("Sum of rows" , my_2d_array.sum(axis = 1))

print("Min", my_2d_array.min())

print("Mean", my_2d_array.mean())

print("Sum", my_2d_array.sum())

print("Std", my_2d_array.std())

Max 7
Max in column [7 7 7]
Max in row [7 7]
Sum of coulmn [14 10 14]
Sum of rows [17 21]
Min 3
Mean 6.333333333333333
Sum 38
Std 1.4907119849998596


In [44]:
a = my_2d_array[0]
print(a)

[7 3 7]


In [45]:
a = my_2d_array[0][1]
print(a)

3


In [46]:
x =np.array([[1,2],[3,4],[5,6]])
y = np .array([[1,2,3],[4,5,6]])
np.dot(x,y)

array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]])

In [146]:
# Re-shape (here to 3 rows & 2 columns)

print(a)
print(" ------- ")
a = my_2d_array.reshape(3,2)
print(my_2d_array)


[[2 1]
 [3 1]
 [2 1]]
 ------- 
[[2 1 3]
 [1 2 1]]


In [158]:
x = np.arange(12).reshape((2,2,3)) #2 blocks each block (2,3)
x

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [149]:
print(x)
print(" --- 1D --- " )
x.ravel()

[[0 1 2]
 [3 4 5]
 [6 7 8]]
 --- 1D --- 


array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [155]:
# Re-shape (here to a 1-Dimensional array)
print(" --- ND to 1D --- " )

a = x.flatten()
print(a)
print(" --- ND to 1D --- " )

a = x.reshape(9)
print(a)

print(" --- ND to 1D --- " )

a = x.ravel()
print(a)

 --- ND to 1D --- 
[0 1 2 3 4 5 6 7 8]
 --- ND to 1D --- 
[0 1 2 3 4 5 6 7 8]
 --- ND to 1D --- 
[0 1 2 3 4 5 6 7 8]


In [159]:
# Array Shape (length of each dimension)
a = my_2d_array.shape
print(a)

(2, 3)


In [52]:
# Number of dimensions
a = my_2d_array.ndim
print(a)

2


In [53]:
# Number of elements
a = my_2d_array.size
print(a)

6


In [54]:
a = my_2d_array.dtype
print(a)

int64


In [55]:
b = np.array([1,2,3])
c = np.array([4,2,6])
print("b", b)
print("c", c)

b [1 2 3]
c [4 2 6]


In [56]:
a = np.add(b,c)
print(a)

[5 4 9]


In [57]:
a = np.subtract(b,c)
print(a)

[-3  0 -3]


In [58]:
a = np.multiply(b,c)
print(a)

[ 4  4 18]


In [59]:
a = np.divide(b,c)
print(a)

[0.25 1.   0.5 ]


In [60]:
a = np.dot(b,c)
print(a)

26


In [61]:
a = (b == c)
print(a)

[False  True False]


In [62]:
a = np.array_equal(a,b)
print(a)

False


In [164]:
x = np.arange(3).reshape((3,1))

print(x)
print("---- T ----")
y = x.T

print(y)

[[0]
 [1]
 [2]]
---- T ----
[[0 1 2]]


In [165]:
# Horizontal Stack
# hstack concatenates arrays along axis 1
a = np.hstack((b,c))
print(a)
print("-----")
a = np.concatenate((b,c))
print(a)

[1 2 3 4 2 6]
-----
[1 2 3 4 2 6]


In [65]:
# Vertical Stack
# vstack concatenates arrays along axis 0
a = np.vstack((b,c))
print(a)
print()

x = np.array([[1,2],[3,4]])
y = np.array([[5,6]])
a = np.concatenate((x,y), axis = 0)
a1 = np.vstack((x,y))
print(a)
print(a1)

[[1 2 3]
 [4 2 6]]

[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [66]:
p = np.pi
print(p)

3.141592653589793


In [67]:
a = np.array([1,2,3], dtype = np.float32)
print(a)

[1. 2. 3.]


In [68]:
#Return a 2-D array with ones on the diagonal and zero elsewhere
a = np.eye(3) # with 3 column
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [69]:
a = np.arange(12).reshape(2,2,3)
print(a)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [70]:
# Arrays can be transposed using the .T attribute
a = my_1d_array.T
a1 = my_1d_array.transpose()
print(a)
print(a1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [71]:
#Numpy also provides a set of element-wise functions that can be applied to all elements of an array, creating a new array
a = np.array([[1,2,3],[4,5,6]])
a1 = np.exp(a)
print(a1)
a2 = np.log(a)
print(a2)

[[  2.71828183   7.3890561   20.08553692]
 [ 54.59815003 148.4131591  403.42879349]]
[[0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947]]


In [72]:
# execution time
s = 0
N = 10000000
x = np.arange(N)
for i in x:
  s += i

In [73]:
# execution time
N = 10000000
x = np.arange(N)
s = x.sum()

In [74]:
x = np.arange(15).reshape(3,5)
print(x)

print()
a = x[1, 0:3]
print(a)

print()
a = x[0:2, 0:2]
print(a)

print()
idx = np.array([0, 0, 2])
#means "select the rows of x indexed by idx and all columns (: means all columns)."
a = x[idx, :]
print(a)

print()
#means "select all rows (:) and the columns of x indexed by idx."
a = x[ :,idx]
print(a)

print()
idx = np.array([0,2]) # rows
jdx = np.array([1,3]) # columns
a = x[idx, :][:,jdx]
print(a)

print()
#_ix allows you to create a 2D array by selecting all combinations of rows in idx and columns in jdx
a = x[np.ix_(idx, jdx)] # generates two 2D arrays that can be used to index the original array x:
print(a)

print()
xMask = x > 5
print(xMask)

print()
a = x[xMask]
print(a)

print()
z = np.array([1,0,1], dtype= np.bool_)
print(z)
a = x[z] # z = [True, False, True] -> x[z] = first row and second row
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

[5 6 7]

[[0 1]
 [5 6]]

[[ 0  1  2  3  4]
 [ 0  1  2  3  4]
 [10 11 12 13 14]]

[[ 0  0  2]
 [ 5  5  7]
 [10 10 12]]

[[ 1  3]
 [11 13]]

[[ 1  3]
 [11 13]]

[[False False False False False]
 [False  True  True  True  True]
 [ True  True  True  True  True]]

[ 6  7  8  9 10 11 12 13 14]

[ True False  True]
[[ 0  1  2  3  4]
 [10 11 12 13 14]]


In [75]:
x = np.zeros(6)
print(x)
x[::2] = 3
print(x)


[0. 0. 0. 0. 0. 0.]
[3. 0. 3. 0. 3. 0.]


In [76]:
x[np.array([True, False, True, True, True, False],dtype=np.bool_)] = np.arange(4)
# [0,2,3,4] = [1,2,3,4]
print(x)

[0. 0. 1. 2. 3. 0.]


In [77]:
# copy of the data
x = np.arange(6)
a = x.flags.owndata
print(a)

# view of the data
a = x[:3]
print(a.flags.owndata)


True
False


In [78]:
#Array m is broadcasted to a shape (1, 4), and then replicated along axis 0
x = np.zeros((3,4))
print(x)
print()

m = np.arange(4)
print(m)
print()

a = x + m
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[0 1 2 3]

[[0. 1. 2. 3.]
 [0. 1. 2. 3.]
 [0. 1. 2. 3.]]


In [79]:
# Array m already has the same number of dimensions as x, and gets replicated along axis 0
x = np.zeros((3,4))
print(x)
print()

m = np.arange(4).reshape((1,4))
print(m)
print()

a = x + m
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[0 1 2 3]]

[[0. 1. 2. 3.]
 [0. 1. 2. 3.]
 [0. 1. 2. 3.]]


In [80]:
#Array m already has the same number of dimensions as x, and gets replicated along axis 1
x = np.zeros((3,4))
print(x)
print()

m = np.arange(3).reshape((3,1))
print(m)
print()

a = x + m
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[0]
 [1]
 [2]]

[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]]


In [81]:
# linear algebra functions
# compute the eigenvalue decomposition of a 2-D array
x = np.arange(9).reshape(3,3)
a = np.linalg.eig(x)
print(a)

EigResult(eigenvalues=array([ 1.33484692e+01, -1.34846923e+00, -2.48477279e-16]), eigenvectors=array([[ 0.16476382,  0.79969966,  0.40824829],
       [ 0.50577448,  0.10420579, -0.81649658],
       [ 0.84678513, -0.59128809,  0.40824829]]))


In [82]:
x = np.array([99,1,109,-1])
print(x)
print()

a = np.argsort(x) # index of the sorted array
print(a)
print()

a = np.sort(x)
print(a)
print()

[ 99   1 109  -1]

[3 1 0 2]

[ -1   1  99 109]



In [83]:
x = np.array([99,2,109,-1])
print(x[x>100])
print(x[(x>100) | (x < 0)])
print(x[(x % 2) == 0 ])

[109]
[109  -1]
[2]


In [84]:
x = np.array([99,2,109,-1])
print(x)
a = np.flip(x)
print(a)

[ 99   2 109  -1]
[ -1 109   2  99]


In [85]:
x = np.array([[1,2,3],[4,5,6]])
print(x)
print()

a = np.flip(x)
print(a)
print()

a1 = np.flip(x, axis=0) #column
print(a1)
print()

a2 = np.flip(x, axis=1) #row
print(a2)
print()

[[1 2 3]
 [4 5 6]]

[[6 5 4]
 [3 2 1]]

[[4 5 6]
 [1 2 3]]

[[3 2 1]
 [6 5 4]]



In [86]:
#save array in a file
#np.save('filename' , array)

#load file
#np.load('filename.py')


In [87]:
s =0
N= 10000000
x = np.arange(N)
for i in x:
  s += i

#3s

In [88]:
N= 10000000
x = np.arange(N)

s = x.sum()
#0.127s

In [89]:
x = np.arange(5)
print(x,"--->",x[1:3],x[::2],x[3])

[0 1 2 3 4] ---> [1 2] [0 2 4] 3


In [90]:
x = np.arange(15).reshape(3,5)
print(x, "------", x[1,0:3], x[0:2, 0:2])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]] ------ [5 6 7] [[0 1]
 [5 6]]


In [91]:
idx = np.array([0,0,2])
print(idx)

[0 0 2]


In [92]:
print(x[idx,:]) #x[[0,0,2], :] [row 0, row 0, row 2]

[[ 0  1  2  3  4]
 [ 0  1  2  3  4]
 [10 11 12 13 14]]


In [93]:
 #x[:, [0,0,2]] [column 0, column 0, column 2]
x[:,idx]

array([[ 0,  0,  2],
       [ 5,  5,  7],
       [10, 10, 12]])

In [94]:
 #x[0,0] x[0,0] x[2,2]
x[idx,idx]

array([ 0,  0, 12])

In [95]:
x[idx,:][:,idx]

array([[ 0,  0,  2],
       [ 0,  0,  2],
       [10, 10, 12]])

In [96]:
idx = np.array([0,2])
jdx = np.array([1,3])

In [97]:
#extract all rows in idx and all columns in jdx
#first way

x[idx,:][:,jdx]

array([[ 1,  3],
       [11, 13]])

In [98]:
#second way
x[np.ix_(idx,jdx)]

array([[ 1,  3],
       [11, 13]])

In [99]:
x[idx.reshape((2,1)),jdx.reshape((1,2))]

array([[ 1,  3],
       [11, 13]])

In [100]:
xMask = x>5
print(xMask)

[[False False False False False]
 [False  True  True  True  True]
 [ True  True  True  True  True]]


In [101]:
x[xMask]


array([ 6,  7,  8,  9, 10, 11, 12, 13, 14])

In [102]:
z = np.array([1,0,1], dtype =np.bool)
z

array([ True, False,  True])

In [103]:
x[z]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14]])

In [104]:
x = np.zeros(6)
x

array([0., 0., 0., 0., 0., 0.])

In [105]:
x[::2] = 3 #select every second element, starting from index 0
x

array([3., 0., 3., 0., 3., 0.])

In [106]:
x[np.array([True, False, True, True, True, False], dtype = np.bool)] = np.arange(4)
x
#[0,2,3,4]

array([0., 0., 1., 2., 3., 0.])

In [107]:
x = np.arange(5)
y = x[0:3]
y[:] = 3
print(x)

[3 3 3 3 4]


In [108]:
x = np.arange(5)
x.flags.owndata

True

In [109]:
y = x[0:3]
y.flags.owndata

False

In [110]:
x = np.zeros((3,4))
m = np.arange(4) #m is brodcasted to a shape(1,4) and then replicated along axis 0
print(x+m)

[[0. 1. 2. 3.]
 [0. 1. 2. 3.]
 [0. 1. 2. 3.]]


In [111]:
x = np.zeros((3,4))
m = np.arange(4).reshape((1,4))
x + m

array([[0., 1., 2., 3.],
       [0., 1., 2., 3.],
       [0., 1., 2., 3.]])

In [112]:
x = np.zeros((3,4))
m = np.arange(3).reshape((3,1))
x + m

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.]])

In [113]:
x1 = np.array([[1,2,3]])
x2 = np.array([[4,5,6]])
print(x1,x2)

[[1 2 3]] [[4 5 6]]


In [114]:
np.hstack([x1,x2]) #concatenates arrays along axis 1

array([[1, 2, 3, 4, 5, 6]])

In [115]:
np.vstack([x1,x2]) #concatenates arrays along axis 0

array([[1, 2, 3],
       [4, 5, 6]])

In [116]:
np.concatenate([x1,x2],axis=1) #hstack

array([[1, 2, 3, 4, 5, 6]])

In [117]:
np.concatenate([x1,x2],axis=0) #vstack

array([[1, 2, 3],
       [4, 5, 6]])

In [118]:
x = np.arange(9).reshape(3,3)
np.linalg.eig(x)

EigResult(eigenvalues=array([ 1.33484692e+01, -1.34846923e+00, -2.48477279e-16]), eigenvectors=array([[ 0.16476382,  0.79969966,  0.40824829],
       [ 0.50577448,  0.10420579, -0.81649658],
       [ 0.84678513, -0.59128809,  0.40824829]]))